const languages = [
  "Abkhazian",
  "Achinese",
  "Acoli",
  "Adangme",
  "Adyghe",
  "Afar",
  "Afrihili",
  "Afrikaans",
  "Aghem",
  "Ainu",
  "Akan",
  "Akkadian",
  "Akoose",
  "Alabama",
  "Albanian",
  "Aleut",
  "Algerian Arabic",
  "American English",
  "American Sign Language",
  "Amharic",
  "Ancient Egyptian",
  "Ancient Greek",
  "Angika",
  "Ao Naga",
  "Arabic",
  "Aragonese",
  "Aramaic",
  "Araona",
  "Arapaho",
  "Arawak",
  "Armenian",
  "Aromanian",
  "Arpitan",
  "Assamese",
  "Asturian",
  "Asu",
  "Atsam",
  "Australian English",
  "Austrian German",
  "Avaric",
  "Avestan",
  "Awadhi",
  "Aymara",
  "Azerbaijani",
  "Badaga",
  "Bafia",
  "Bafut",
  "Bakhtiari",
  "Balinese",
  "Baluchi",
  "Bambara",
  "Bamun",
  "Banjar",
  "Basaa",
  "Bashkir",
  "Basque",
  "Batak Toba",
  "Bavarian",
  "Beja",
  "Belarusian",
  "Bemba",
  "Bena",
  "Bengali",
  "Betawi",
  "Bhojpuri",
  "Bikol",
  "Bini",
  "Bishnupriya",
  "Bislama",
  "Blin",
  "Blissymbols",
  "Bodo",
  "Bosnian",
  "Brahui",
  "Braj",
  "Brazilian Portuguese",
  "Breton",
  "British English",
  "Buginese",
  "Bulgarian",
  "Bulu",
  "Buriat",
  "Burmese",
  "Caddo",
  "Cajun French",
  "Canadian English",
  "Canadian French",
  "Cantonese",
  "Capiznon",
  "Carib",
  "Catalan",
  "Cayuga",
  "Cebuano",
  "Central Atlas Tamazight",
  "Central Dusun",
  "Central Kurdish",
  "Central Yupik",
  "Chadian Arabic",
  "Chagatai",
  "Chamorro",
  "Chechen",
  "Cherokee",
  "Cheyenne",
  "Chibcha",
  "Chiga",
  "Chimborazo Highland Quichua",
  "Chinese",
  "Chinook Jargon",
  "Chipewyan",
  "Choctaw",
  "Church Slavic",
  "Chuukese",
  "Chuvash",
  "Classical Newari",
  "Classical Syriac",
  "Colognian",
  "Comorian",
  "Congo Swahili",
  "Coptic",
  "Cornish",
  "Corsican",
  "Cree",
  "Creek",
  "Crimean Turkish",
  "Croatian",
  "Czech",
  "Dakota",
  "Danish",
  "Dargwa",
  "Dazaga",
  "Delaware",
  "Dinka",
  "Divehi",
  "Dogri",
  "Dogrib",
  "Duala",
  "Dutch",
  "Dyula",
  "Dzongkha",
  "Eastern Frisian",
  "Efik",
  "Egyptian Arabic",
  "Ekajuk",
  "Elamite",
  "Embu",
  "Emilian",
  "English",
  "Erzya",
  "Esperanto",
  "Estonian",
  "European Portuguese",
  "European Spanish",
  "Ewe",
  "Ewondo",
  "Extremaduran",
  "Fang",
  "Fanti",
  "Faroese",
  "Fiji Hindi",
  "Fijian",
  "Filipino",
  "Finnish",
  "Flemish",
  "Fon",
  "Frafra",
  "French",
  "Friulian",
  "Fulah",
  "Ga",
  "Gagauz",
  "Galician",
  "Gan Chinese",
  "Ganda",
  "Gayo",
  "Gbaya",
  "Geez",
  "Georgian",
  "German",
  "Gheg Albanian",
  "Ghomala",
  "Gilaki",
  "Gilbertese",
  "Goan Konkani",
  "Gondi",
  "Gorontalo",
  "Gothic",
  "Grebo",
  "Greek",
  "Guarani",
  "Gujarati",
  "Gusii",
  "Gwich\u02bcin",
  "Haida",
  "Haitian",
  "Hakka Chinese",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Herero",
  "Hiligaynon",
  "Hindi",
  "Hiri Motu",
  "Hittite",
  "Hmong",
  "Hungarian",
  "Hupa",
  "Iban",
  "Ibibio",
  "Icelandic",
  "Ido",
  "Igbo",
  "Iloko",
  "Inari Sami",
  "Indonesian",
  "Ingrian",
  "Ingush",
  "Interlingua",
  "Interlingue",
  "Inuktitut",
  "Inupiaq",
  "Irish",
  "Italian",
  "Jamaican Creole English",
  "Japanese",
  "Javanese",
  "Jju",
  "Jola-Fonyi",
  "Judeo-Arabic",
  "Judeo-Persian",
  "Jutish",
  "Kabardian",
  "Kabuverdianu",
  "Kabyle",
  "Kachin",
  "Kaingang",
  "Kako",
  "Kalaallisut",
  "Kalenjin",
  "Kalmyk",
  "Kamba",
  "Kanembu",
  "Kannada",
  "Kanuri",
  "Kara-Kalpak",
  "Karachay-Balkar",
  "Karelian",
  "Kashmiri",
  "Kashubian",
  "Kawi",
  "Kazakh",
  "Kenyang",
  "Khasi",
  "Khmer",
  "Khotanese",
  "Khowar",
  "Kikuyu",
  "Kimbundu",
  "Kinaray-a",
  "Kinyarwanda",
  "Kirmanjki",
  "Klingon",
  "Kom",
  "Komi",
  "Komi-Permyak",
  "Kongo",
  "Konkani",
  "Korean",
  "Koro",
  "Kosraean",
  "Kotava",
  "Koyra Chiini",
  "Koyraboro Senni",
  "Kpelle",
  "Krio",
  "Kuanyama",
  "Kumyk",
  "Kurdish",
  "Kurukh",
  "Kutenai",
  "Kwasio",
  "Kyrgyz",
  "K\u02bciche\u02bc",
  "Ladino",
  "Lahnda",
  "Lakota",
  "Lamba",
  "Langi",
  "Lao",
  "Latgalian",
  "Latin",
  "Latin American Spanish",
  "Latvian",
  "Laz",
  "Lezghian",
  "Ligurian",
  "Limburgish",
  "Lingala",
  "Lingua Franca Nova",
  "Literary Chinese",
  "Lithuanian",
  "Livonian",
  "Lojban",
  "Lombard",
  "Low German",
  "Lower Silesian",
  "Lower Sorbian",
  "Lozi",
  "Luba-Katanga",
  "Luba-Lulua",
  "Luiseno",
  "Lule Sami",
  "Lunda",
  "Luo",
  "Luxembourgish",
  "Luyia",
  "Maba",
  "Macedonian",
  "Machame",
  "Madurese",
  "Mafa",
  "Magahi",
  "Main-Franconian",
  "Maithili",
  "Makasar",
  "Makhuwa-Meetto",
  "Makonde",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manchu",
  "Mandar",
  "Mandingo",
  "Manipuri",
  "Manx",
  "Maori",
  "Mapuche",
  "Marathi",
  "Mari",
  "Marshallese",
  "Marwari",
  "Masai",
  "Mazanderani",
  "Medumba",
  "Mende",
  "Mentawai",
  "Meru",
  "Meta\u02bc",
  "Mexican Spanish",
  "Micmac",
  "Middle Dutch",
  "Middle English",
  "Middle French",
  "Middle High German",
  "Middle Irish",
  "Min Nan Chinese",
  "Minangkabau",
  "Mingrelian",
  "Mirandese",
  "Mizo",
  "Modern Standard Arabic",
  "Mohawk",
  "Moksha",
  "Moldavian",
  "Mongo",
  "Mongolian",
  "Morisyen",
  "Moroccan Arabic",
  "Mossi",
  "Multiple Languages",
  "Mundang",
  "Muslim Tat",
  "Myene",
  "Nama",
  "Nauru",
  "Navajo",
  "Ndonga",
  "Neapolitan",
  "Nepali",
  "Newari",
  "Ngambay",
  "Ngiemboon",
  "Ngomba",
  "Nheengatu",
  "Nias",
  "Niuean",
  "No linguistic content",
  "Nogai",
  "North Ndebele",
  "Northern Frisian",
  "Northern Sami",
  "Northern Sotho",
  "Norwegian",
  "Norwegian Bokm\u00e5l",
  "Norwegian Nynorsk",
  "Novial",
  "Nuer",
  "Nyamwezi",
  "Nyanja",
  "Nyankole",
  "Nyasa Tonga",
  "Nyoro",
  "Nzima",
  "N\u02bcKo",
  "Occitan",
  "Ojibwa",
  "Old English",
  "Old French",
  "Old High German",
  "Old Irish",
  "Old Norse",
  "Old Persian",
  "Old Proven\u00e7al",
  "Oriya",
  "Oromo",
  "Osage",
  "Ossetic",
  "Ottoman Turkish",
  "Pahlavi",
  "Palatine German",
  "Palauan",
  "Pali",
  "Pampanga",
  "Pangasinan",
  "Papiamento",
  "Pashto",
  "Pennsylvania German",
  "Persian",
  "Phoenician",
  "Picard",
  "Piedmontese",
  "Plautdietsch",
  "Pohnpeian",
  "Polish",
  "Pontic",
  "Portuguese",
  "Prussian",
  "Punjabi",
  "Quechua",
  "Rajasthani",
  "Rapanui",
  "Rarotongan",
  "Riffian",
  "Romagnol",
  "Romanian",
  "Romansh",
  "Romany",
  "Rombo",
  "Root",
  "Rotuman",
  "Roviana",
  "Rundi",
  "Russian",
  "Rusyn",
  "Rwa",
  "Saho",
  "Sakha",
  "Samaritan Aramaic",
  "Samburu",
  "Samoan",
  "Samogitian",
  "Sandawe",
  "Sango",
  "Sangu",
  "Sanskrit",
  "Santali",
  "Sardinian",
  "Sasak",
  "Sassarese Sardinian",
  "Saterland Frisian",
  "Saurashtra",
  "Scots",
  "Scottish Gaelic",
  "Selayar",
  "Selkup",
  "Sena",
  "Seneca",
  "Serbian",
  "Serbo-Croatian",
  "Serer",
  "Seri",
  "Shambala",
  "Shan",
  "Shona",
  "Sichuan Yi",
  "Sicilian",
  "Sidamo",
  "Siksika",
  "Silesian",
  "Simplified Chinese",
  "Sindhi",
  "Sinhala",
  "Skolt Sami",
  "Slave",
  "Slovak",
  "Slovenian",
  "Soga",
  "Sogdien",
  "Somali",
  "Soninke",
  "South Azerbaijani",
  "South Ndebele",
  "Southern Altai",
  "Southern Sami",
  "Southern Sotho",
  "Spanish",
  "Sranan Tongo",
  "Standard Moroccan Tamazight",
  "Sukuma",
  "Sumerian",
  "Sundanese",
  "Susu",
  "Swahili",
  "Swati",
  "Swedish",
  "Swiss French",
  "Swiss German",
  "Swiss High German",
  "Syriac",
  "Tachelhit",
  "Tagalog",
  "Tahitian",
  "Taita",
  "Tajik",
  "Talysh",
  "Tamashek",
  "Tamil",
  "Taroko",
  "Tasawaq",
  "Tatar",
  "Telugu",
  "Tereno",
  "Teso",
  "Tetum",
  "Thai",
  "Tibetan",
  "Tigre",
  "Tigrinya",
  "Timne",
  "Tiv",
  "Tlingit",
  "Tok Pisin",
  "Tokelau",
  "Tongan",
  "Tornedalen Finnish",
  "Traditional Chinese",
  "Tsakhur",
  "Tsakonian",
  "Tsimshian",
  "Tsonga",
  "Tswana",
  "Tulu",
  "Tumbuka",
  "Tunisian Arabic",
  "Turkish",
  "Turkmen",
  "Turoyo",
  "Tuvalu",
  "Tuvinian",
  "Twi",
  "Tyap",
  "Udmurt",
  "Ugaritic",
  "Ukrainian",
  "Umbundu",
  "Unknown Language",
  "Upper Sorbian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Vai",
  "Venda",
  "Venetian",
  "Veps",
  "Vietnamese",
  "Volap\u00fck",
  "V\u00f5ro",
  "Votic",
  "Vunjo",
  "Walloon",
  "Walser",
  "Waray",
  "Warlpiri",
  "Washo",
  "Wayuu",
  "Welsh",
  "West Flemish",
  "Western Frisian",
  "Western Mari",
  "Wolaytta",
  "Wolof",
  "Wu Chinese",
  "Xhosa",
  "Xiang Chinese",
  "Yangben",
  "Yao",
  "Yapese",
  "Yemba",
  "Yiddish",
  "Yoruba",
  "Zapotec",
  "Zarma",
  "Zaza",
  "Zeelandic",
  "Zenaga",
  "Zhuang",
  "Zoroastrian Dari",
  "Zulu",
  "Zuni",
];
const countries = [
  "Afghanistan",
  "\u00c5land Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "United States Minor Outlying Islands",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cabo Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo (Democratic Republic of the)",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cura\u00e7ao",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Vatican City",
  "Honduras",
  "Hungary",
  "Hong Kong",
  "Iceland",
  "India",
  "Indonesia",
  "Ivory Coast",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "North Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Korea (Democratic People's Republic of)",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of Kosovo",
  "R\u00e9union",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barth\u00e9lemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Korea (Republic of)",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "South Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Vietnam",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export { languages, countries };
